# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:52
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allo_transport', '0004_auto_20170303_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='page',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='page',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='photo',
        ),
        migrations.AddField(
            model_name='newspage',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
