# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0018_remove_rendition_filter'),
        ('allo_transport', '0005_auto_20170303_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
