# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allo_transport', '0007_auto_20170303_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspage',
            name='apercu',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
