# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allo_transport', '0011_homepage_body_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='blue_body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blue_body_title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
