# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-23 12:11
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allo_transport', '0012_auto_20170306_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body_title',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
